server:
  port: 9090
local: localhost:8848
origin: 47.120.13.165:8848
spring:
  application:
    name: @artifactId@
#  cloud:
#    nacos:
#      discovery:
#        server-addr: ${origin}
#      config:
#        server-addr: ${origin}
  cloud:
    nacos:
      discovery:
        server-addr: ${origin}
      config:
        server-addr: ${origin}
  config:
    import:
      - optional:nacos:common.yaml
logging:
  file:
    name: logs/application/application.log
