spring:
  cloud:
    openfeign:
      client:
        config:
          defalut: # 全局配置、局部配置需写为服务名
            loggerLevel: FULL # 日志级别
      httpclient:
        enabled: true # 开启openFeign对httpclient的支持
        max-connections: 200  # 最大连接数
        max-connections-per-route: 50 # 每个路径的最大连接数
feign:
  sentinel:
    enabled: true # 开启feign的Sentinel
#  在启动类添加注解@EnableFeignClients(若无法使用clients，需指明clients包的位置，
#  如：basePackages="com.hncj.clients"或clients={UserClient.class})

