server:
  port: 10010
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
  file:
    name: logs/gateway/gateway.log
spring:
  application:
    name: @artifactId@
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      # sentinel持久化
      datasource:
        flow:
          nacos:
            server-addr: localhost:8848 # nacos地址
            dataId: gateway-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: flow # 还可以是：degrade、authority、param-flow
    nacos:
      server-addr: localhost:8848 # nacos地址
      config:
        import-check:
          enabled: false
    gateway:
      routes:
        - id: test # 路由标示，必须唯一
          uri: lb://test # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/hello/** # 路径断言，判断路径是否是以/user开头，如果是则符合
      default-filters:
        - AddRequestHeader=Truth,go
