server:
  port: 9091
spring:
  application:
    name: hello
  config:
    import:
      - optional:nacos:common.yaml
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
      #        import-check:
#          enabled: false
      discovery:
        server-addr: localhost:8848


