spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
#  spring:
#    cloud:
#      sentinel:
#        datasource:
#          flow:
#            nacos:
#              server-addr: localhost:8848 # nacos地址
#              dataId: 服务名-flow-rules
#              groupId: SENTINEL_GROUP
#              rule-type: flow # 还可以是：degrade、authority、param-flow
